# Config dir
ZSH_CONFIG_DIR=$HOME/.config/zsh

source $ZSH_CONFIG_DIR/config.zsh
source $ZSH_CONFIG_DIR/aliases.zsh
source $ZSH_CONFIG_DIR/plugins.zsh
source $ZSH_CONFIG_DIR/bindings.zsh
source $ZSH_CONFIG_DIR/functions.zsh

# Powerlevel10k zsh config
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
