#!/bin/sh

# Startup
setxkbmap -layout us,latam -option grp:alt_shift_toggle &
numlockx

pgrep -x sxhkd > /dev/null || sxhkd &

compton --config $HOME/.config/compton/compton.conf &

feh --bg-fill $HOME/Pictures/Wallpapers/wallpaper.jpg &

wmname LG3D &

$HOME/.config/polybar/scripts/launch.sh &

pgrep telegram > /dev/null || telegram-desktop &

bspc config pointer_modifier mod1
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding			0
bspc config right_padding		0
bspc config bottom_padding 		0
bspc config left_padding 		0
bspc config border_width 		2
bspc config window_gap 			10

bspc config normal_border_color 	"#252525"
bspc config focused_border_color 	"#0050B7"
bspc config presel_feedback_color 	"#89B8F7"

bspc config split_ratio 		0.52
bspc config borderless_monocle 		true
bspc config gapless_monocle 		true
bspc config focus_follows_pointer 	true

# [Deprecated] Brave picture in picture 
#bspc config external_rules_command $HOME/.config/bspwm/scripts/external_rules

bspc rule -a dolphin state=floating follow=on
bspc rule -a rimworldwin64.exe desktop='^7' follow=on focus=on
bspc rule -a TelegramDesktop desktop='^10'
bspc rule -a Spotify desktop='^9'
# Auhty brave extension
bspc rule -a Brave-browser:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb dekstop='^8' state=floating follow=on
# Picture in picture brave
bspc rule -a *:*:"Picture in picture" state=floating
