#!/bin/sh

# Startup.
$HOME/Scripts/startup.sh

# Monitors.
if [[ $(xrandr --query | grep ' connected' | wc -l) = 2 ]]; then
	bspc monitor eDP1 -d I II III IV V
	bspc monitor HDMI1 -d VI VII VIII IX X
else
	bspc monitor HDMI1 -r
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
fi

bspc config pointer_modifier mod1

bspc config top_padding			0
bspc config right_padding		0
bspc config bottom_padding 		0
bspc config left_padding 		0
bspc config border_width 		2
bspc config window_gap 			3

bspc config normal_border_color 	"#252525"
bspc config focused_border_color 	"#0050B7"
bspc config presel_feedback_color 	"#89B8F7"

bspc config split_ratio 		0.52
bspc config borderless_monocle 		true
bspc config gapless_monocle 		true
bspc config focus_follows_pointer 	false

bspc rule -a dolphin state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on 
bspc rule -a rimworldwin64.exe desktop='^5' follow=on focus=on
bspc rule -a Spotify desktop='^8'
bspc rule -a Slack desktop='^9'
bspc rule -a TelegramDesktop desktop='^10'

# Terminator
bspc rule -a Terminator:terminator:"Terminator Preferences" state=floating follow=on

# Android studio.
bspc rule -a jetbrains-studio
bspc rule -a jetbrains-studio:sun-awt-X11-XFramePeer:"Welcome to Android Studio" state=floating
bspc rule -a jetbrains-studio:sun-awt-X11-XWindowPeer:"win0" state=floating 

# Picture in picture.
bspc rule -a *:*:"Picture in picture" state=floating

# Authy (Brave extension).
bspc rule -a Brave-browser:crx_gaedmjdfmmahhbjefcbgaolhhanlaolb state=floating follow=on
